version: "3.8"

services:
  hyla-backend-update:
    build:
      context: .
      target: builder
    image: hyla:backend
    container_name: hyla-backend-update
    ports:
      - "8000:8100"
    volumes:
      - ./.env:/app/.env
    command: npm run start:prod
