version: "3.8"

services:
  hyla-backend:
    build:
      context: .
      target: builder
    image: hyla:backend-dev
    container_name: hyla-backend-update
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env
    command: npm run start:prod
